spring:
  datasource:
    url: jdbc:postgresql://10.1.0.3:5432/adolescent_dev_program_prod
    username: adolescent_user
    password: Adolescent@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
