spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:adolescent_dev_program
    username: adolescent_user
    password: Adolescent@123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
  sql:
    init:
      mode: always
